apiVersion: v1
kind: Service
metadata:
  name: spire-agent
  namespace: zero-trust-workload-identity-manager
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: spire
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/managed-by: "zero-trust-workload-identity-manager"
    app.kubernetes.io/part-of: "zero-trust-workload-identity-manager"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9402
      targetPort: 9402
      protocol: http
  selector:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: spire
