apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    control-plane: controller-manager
  name: zero-trust-workload-identity-manager-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
