apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: zero-trust-workload-identity-manager
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/created-by: zero-trust-workload-identity-manager
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: kustomize
    control-plane: controller-manager
  name: metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
