# permissions for end users to view zerotrustworkloadidentitymanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: kustomize
  name: zerotrustworkloadidentitymanager-viewer-role
rules:
- apiGroups:
  - operator.openshift.io.operator.openshift.io
  resources:
  - zerotrustworkloadidentitymanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io.operator.openshift.io
  resources:
  - zerotrustworkloadidentitymanagers/status
  verbs:
  - get
